### ISSUE TITLE
Store NMEA file if bluetooth not connected / enabled

### ISSUE THREAD

**Issue by nikolauskrismer** [rp-/BlueMouse#3]
Is it possible to store the NMEA data (which is usally sent by bluetooth) to the phone (sd-card?) if there is no connected bluetooth device (or bluetooth disabled)?

When doing this, data could be written to xmp files using exiftool and therefore also be used with pictures taken by any DSLR camera (foolography is much better since it writes data directly to raw/jpg files)

**Comment by rp-** [comment]
It would be possible, but I think a dedicated tracking app would be better suited for that.
Like My Tracks or OsmAnd.
You can save the .gpx files and then combine it with the timestamp of your pictures, most of the photo software can do this.

**Comment by nikolauskrismer** [comment]
You might be right.

I did not know about OsmAnd (looks great) and didn't want to give google (myTracks) more data about me (they already know too much... they do not need to know where I am).
It would be amazing if there was some integration of blutooth (for communication with foolography) into OsmAnd (or locus), but I guess that this would mean quite some work :)

Thanks for your application hints.. they helped me a lot :+1:

**Comment by rp-** [comment]
Well you can have both apps running in parallel, BlueMouse handling the foolography requests and another app recording your track.
This shouldn't make any problems.
