### ISSUE TITLE
Google Galaxy I9250 4.2.2 Stock

### ISSUE THREAD

**Issue by EIBHomeControl** [rp-/BlueMouse#4]
Hi,

i've tried to pair the foolography with the Google Galaxy I9250. But it's not working.
1st time i'll be ask for the pin 0000. So the 2nd try would fail.
Any ideas how i can get the bluemouse working with the foolography?

Is a recompile with the 4.2.2 SDK an option?
Frank

**Comment by rp-** [comment]
Hi!

You would need to check which ports are already reservered/used from your ROM. With Linux you can use the sdptool. For the foolography port 1 has to be free.
But the galaxy should work imho, but I didn't test anything for a while.

I don't think a recompile would solve the issue.

**Comment by EIBHomeControl** [comment]
Hi,

just attached the device to logcat. rfcomm 1 is already in use.
So is there any chance to close channel 1? Or is it possible to get more information who is using channel 1?

Frank

**Comment by rp-** [comment]
I guess it's android itself and I think your only chance is to use a custom ROM (like cyanogenmod).
It's just awkward because usually the stock android ROM which i guess is used on the galaxy, starts using ports at 10 or 12 up.

**Comment by EIBHomeControl** [comment]
Ok. I'll try to downgrade to 4.1.2. Some users reported this should work.
If it doesn't i'll try a custom rom.
Thanks for your support.
Frank

**Comment by EIBHomeControl** [comment]
Downgrade to 4.1.2 do the trick. Working as expected. Logcat says using channel 1.
